### ISSUE TITLE
incorrect padding crashing Wax on app start

### ISSUE THREAD

**Issue by dfalling** [tanguilp/wax#13]
I'm getting this crash from Wax on startup.  I'm guessing the structure of FIDO's metadata has changed?
```
[error] Task #PID<0.1813.0> started from Wax.Metadata terminating
** (ArgumentError) incorrect padding
    (elixir) lib/base.ex:1107: Base.do_decode64url/2
    (wax) lib/wax/metadata.ex:226: Wax.Metadata.update_metadata_statement/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<3.92563671/0 in Wax.Metadata.process_metadata_toc/2>
    Args: []
```

It looks like a similar error here: https://github.com/techgaun/auth0_ex/issues/10 with the proposed fix of `Base.url_decode64!/2` with `padding: false`.

**Comment by tanguilp** [comment]
Indeed metadata format has changed overnight. It's now conformant with the specification (https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html#notation) and has been pushed on 0.1.3.

Surprisingly, it has been changed for the `hash` (https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html#widl-MetadataTOCPayloadEntry-hash) field but not the `url` content.

**Comment by dfalling** [comment]
Wow, thanks for the quick fix!
