### ISSUE TITLE
Remove Tesla client

### ISSUE THREAD

**Issue by boydm** [tanguilp/wax#20]
Hi. I'm looking at wax and noticed at that deps section in mix.exs brings in the tesla web client, but I can't see anywhere in the code where it is used.

Is it a leftover from the past that can be safely removed? I'd rather not have dependencies loaded that aren't actually being used.

Thanks

**Comment by tanguilp** [comment]
It is used [here](https://github.com/tanguilp/wax/blob/master/lib/wax/metadata.ex#L475-L492) to retrieve metadata.

**Comment by gdgp** [comment]
@tanguilp as I was setting this up on my side, just noticed that the link provided in the documentation no longer exists. 

It seems that they migrated from a V2 of the service to a V3 where they no longer require the API token!

Source: https://fidoalliance.org/metadata/

**Comment by tanguilp** [comment]
Indeed, thanks for the info! I knew about this but last time I checked specification was not available yet. It's now on my todo list :)

**Comment by tanguilp** [comment]
Fixed by https://github.com/tanguilp/wax/pull/23
