### ISSUE TITLE
Incorrect :type values set for Wax.AttestationVerificationErrors

### ISSUE THREAD

**Issue by pzingg** [tanguilp/wax#32]
I think there are some copy-paste typos in the `verify` logic for the `AttestationStatementFormat.FIDOU2F` and `Wax.AttestationStatementFormat.AppleAnonymous` modules. For the former, the `:type` value for any `AttestationVerificationError` returned should probably be `:fido_u2f`, and for the latter, `:apple`.

Also, are these `:type` values supposed to be the same as those in the `Wax.Attestation.statement_format` typespec? 

In which case, `:apple` or `:apple_anonymous` should be added to that typespec, and `:safetynet` should be `:android_safetynet`, and possibly `:apple` should be `:apple_anonymous`...

**Comment by tanguilp** [comment]
Thanks for the report. I’m on holidays for one week, I’ll take a look in two weeks.

**Comment by tanguilp** [comment]
Forgot about this. Going to have a look next week.

**Comment by tanguilp** [comment]
Thanks again for reporting.

> I think there are some copy-paste typos in the verify logic for the AttestationStatementFormat.FIDOU2F and Wax.AttestationStatementFormat.AppleAnonymous modules. For the former, the :type value for any AttestationVerificationError returned should probably be :fido_u2f, and for the latter, :apple.

Fixed in https://github.com/tanguilp/wax/pull/35

> Also, are these :type values supposed to be the same as those in the Wax.Attestation.statement_format typespec?

Well the `Wax.Attestation.statement_format()` type wasn't used anywhere, but now it is in the type declaration for `%Wax.AttestationVerificationError{}`.

> In which case, :apple or :apple_anonymous should be added to that typespec, and :safetynet should be :android_safetynet, and possibly :apple should be :apple_anonymous...

Changed the type enum value to `safetynet` since it was unused and to keep retrocompatiblity.

Feel free to review the PR and comment it.
