### ISSUE TITLE
Should challenge.issued_at use unix time?

### ISSUE THREAD

**Issue by woylie** [tanguilp/wax#38]
I noticed that the `issued_at` value in `Wax.Challenge` is set using `:erlang.monotonic_time/1`. Is there a reason for this choice? It seems a bit problematic to me, since:

1. This value is monotonically increasing, but not strictly monotonically increasing. [Consecutive calls can produce the same result](https://www.erlang.org/doc/man/erlang#monotonic_time-0).
2. The produced value is not the same on different runtime instances. If a challenge is generated on one node, stored in a session, and the verification happens to be handled on a different node, the timeout detection may fail.

Shouldn't the value be the unix time instead? Also, the timeouts in the WebAuthn specification are defined in milliseconds. I think it would be good to use millisecond values in the library as well, to avoid confusion. So in short, `DateTime.to_unix(DateTime.utc_now(), :millisecond)`.

**Comment by tanguilp** [comment]
I think I did it this way for some security reasons: bad actors can succeed in changing the UNIX time (hacking NTP, changing the time on the OS...) and make an expired challenge valid again.

Now, this is probably overstretched as an attack scenario, and the issue with different nodes is real. We probably need to change that as you suggest.

Which issue do you have exactly?

**Comment by woylie** [comment]
I have an implementation where the authenticator response is submitted with a POST request on a controller route. The challenge is stored in a session cookie. In a multi-node deployment, I cannot guarantee that this request is made on the same node that generated the session.

**Comment by tanguilp** [comment]
Ok so this needs to be changed. Going to fix it this WE, check out for a new version on Monday.

Until then, have a good WE!

**Comment by tanguilp** [comment]
Feel free to check and comment https://github.com/tanguilp/wax/pull/39

**Comment by woylie** [comment]
Thank you for the quick release!
