### ISSUE TITLE
Passing FIDO test suite for tpm format

### ISSUE THREAD

**Issue by miguelvillaresb** [tanguilp/wax#41]
To pass the tests for section MakeCredential: Platform Attestations It is required to uncomment the following line code in `Wax.AttestationStatementFormat.TPM`.

```
  ++ ["id:FFFFF1D0"]
  # fake ID for conformance tool testing, uncomment only for testing
```

Maybe this should be included in the README somewhere because It is not explicitly mentioned.

**Comment by tanguilp** [comment]
It's documented here: https://github.com/tanguilp/wax_fido_test_suite_server

If you're running `mix test`, then you're not using the conformance tool and therefore you don't need to uncomment this line.

If you're running the conformance tool, feel free to tell me if it's still passing all the tests (some new are added from time to time).

**Comment by miguelvillaresb** [comment]
Thanks for the link. I didn't see the Enable TMP ID section.

I am running the FIDO conformance test and right now I am finding some issues. I will let you know.

BTW congrats for the great work in these repositories.
