### ISSUE TITLE
Error on MakeCredential: Platform attestations P-2 test

### ISSUE THREAD

**Issue by miguelvillaresb** [tanguilp/wax#42]
**Env**
Erlang OTP-26.2.1
Elixir v1.16.2

**Issue**
Running the FIDO conformance tests, section `MakeCredential: Platform attestations` test P-2, I am getting an exception on erlang library `:public_key`.

<img width="1125" alt="image" src="https://github.com/tanguilp/wax/assets/91469337/bec959a6-db14-4b08-93bc-c083d45c1bfd">

This is the test failing:
<img width="704" alt="image" src="https://github.com/tanguilp/wax/assets/91469337/98fd0576-4f9e-4cba-9993-7c681d973fae">

**Comment by tanguilp** [comment]
Before checking out, is it the only one failing?

**Comment by miguelvillaresb** [comment]
Yes, right now It is the only one failing.

**Comment by tanguilp** [comment]
Looks similar to https://github.com/fido-alliance/conformance-test-tools-resources/issues/709

Tested with Conformance Tool 1.7.20-4, all tests pass.

**Comment by miguelvillaresb** [comment]
I will check with that version. Thanks.

**Comment by miguelvillaresb** [comment]
I found the issue. I am using Rocky Linux for the backend and SHA-1 is disabled by default on new versions. I reactivate SHA-1 by running:

`update-crypto-policies --set DEFAULT:SHA1`

**Comment by tanguilp** [comment]
Great! Thanks for the feedback.
